[versions]
paper = "1.21.11-R0.1-SNAPSHOT"
shadow = "9.3.1"

hikaricp = "7.0.2"
flyway = "12.0.1"
mysql = "9.6.0"
caffeine = "3.2.3"
slf4j = "2.0.17"
annotations = "26.0.2"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
mysql = { module = "com.mysql:mysql-connector-j", version.ref = "mysql" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-jdk14 = { module = "org.slf4j:slf4j-jdk14", version.ref = "slf4j" }

annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
